tinymce.addI18n('en_US_in', {
  "listNumTip": "Numbering",
  "restartListsNum": "Restart numbering",
  "continueListsNum": "Continue numbering",
  "fileTypeNotSupport": "File type unsupported",
  "specialStyleNoFormatBrush": "Format painter not supported for special styles",
  "formatApplyFailed": "Format painter unavailable",
  "syncNoun": "Sync",
  "syncVerb": "Sync",
  "recordTransferFailedAndRetry": "Failed to transcribe. {0}",
  "today": "{0} today",
  "tomorrow": "{0} tomorrow",
  "yesterday": "{0} yesterday",
  "toNextTextPosition": "({0}/{1}) Next part",
  "toOriginTextPosition": "({0}/{1}) Return to AI Summary",
  "originTextNotExit": "Transcript does not exist",
  "loadingData": "Loading",
  "dataLoadError": "Error loading data",
  "dataCannotLoad": "Unable to load data",
  "aiCommandUnselectedTextTip1": "Enter content first",
  "aiCommandLimitedSmartTypesettingTip": "Select at least {0} characters for smart layout",
  "aiCommandInvitationCard": "Invitation",
  "aiCommandWeeklyReportTip": "Enter job content or highlights",
  "aiCommandLimitedMaxTextTip": "Word limit exceeded",
  "aiCommandPest": "PEST analysis",
  "aiCommandResumeTip": "Enter position or experience",
  "aiCommandMomentsTip": "Enter theme",
  "aiCommandApplyTip": "Enter event, time, and place",
  "aiCommandArticleOutlineTip": "Enter topic",
  "aiCommandWorkSummaryTip": "Enter duties or highlights",
  "aiCommandWeeklyReport": "Daily/Weekly report",
  "aiCommandCommon": "Polish",
  "aiCommandExpand": "Extend",
  "aiCommandArticle": "Article",
  "aiCommandLimitedCommonTip": "Select at least {0} characters to polish",
  "aiCommandPffaTip": "Enter subject to get industry insights",
  "aiCommandLeave": "Leave request",
  "aiCommandActivities": "Event plan",
  "aiCommandMoments": "Moments copy",
  "aiCreateMarkText": "AI-generated, for reference only.",
  "aiCommandSwotTip": "Enter subject for analysis",
  "aiCommandPestTip": "Enter subject to get macro-level insights",
  "aiCommandSpeech": "Speech script",
  "aiCommandMeet": "Meeting notification",
  "aiPopSamllTitle2": "Create content in specified format",
  "aiCommandConcise": "Shorten",
  "aiCommandSwot": "SWOT analysis",
  "aiCommandCreativeMind": "Brainstorming",
  "aiCommandApply": "Application",
  "aiCommandCreativeMindTip": "Enter topic or subject",
  "aiCommandDefaultTip": "Enter a creation prompt or choose from the list",
  "aiCommandPoetry": "Write poem",
  "aiCommandPublicTip": "Enter theme",
  "aiCommandContinue": "Continue writing",
  "aiCommandExperienceTip": "Enter thoughts",
  "aiCommandSpeechTip": "Enter topic",
  "aiCommandMeetTip": "Enter meeting info",
  "aiCommandDocSummary": "Summarize",
  "aiCommandResume": "Resume",
  "aiCommandJobDescriptionTip": "Enter job title or responsibilities",
  "aiCommandToDoListTip": "Enter task or goal",
  "aiCommandLimitedConciseTip": "Select at least {0} characters to shorten",
  "aiCommandLeaveTip": "Enter reason and time",
  "aiCommandActivitiesTip": "Enter theme or goal",
  "aiCommandPoetryTip": "Enter theme",
  "aiCommandExperience": "Thoughts",
  "aiCommandRedbook": "rednote copy",
  "aiCommandJobDescription": "Job description",
  "aiCommandSelfIntroduction": "Self-introduction",
  "aiCommandArticleOutline": "Outline",
  "aiCommandInvitationCardTip": "Enter reason and time",
  "aiCommandPublic": "Promotional plan",
  "aiPopSamllTitle1": "Create based on selected text",
  "aiCommandLimitedDocSummaryTip": "Select at least {0} characters to summarize",
  "aiCommandPffa": "Porter's Five Forces analysis",
  "aiCommandSelfIntroductionTip": "Enter basic personal info",
  "aiCommandUnselectedTextTip": "Select text first",
  "aiCommandFixGrammar": "Revise",
  "aiCommandToDoList": "To-do list",
  "aiCommandPressRelease": "Press release",
  "aiCommandWorkSummary": "Work summary",
  "transcribingStatus1": "Transcribing… {0}",
  "aiSelectionOver": "Unable to process over {0} characters",
  "cancel": "Cancel",
  "dontLeaveNoteTips": "Operation in progress. Stay on this page",
  "noteCountWithNum": "Characters: {0}",
  "imgSizeLimit": "Image size cannot exceed 200 MB",
  "recordLoadError": "Error loading recording",
  "editorAiCreating": "Cannot edit note while AI Creation is in progress",
  "recordCannotLoad": "Unable to load recording",
  "imgLoadError": "Error loading image",
  "audioCannotLoad": "Unable to load audio",
  "tuyaCannotLoad": "Unable to load doodle",
  "tuyaLoadError": "Error loading doodle",
  "imgLoading": "Loading image",
  "fileLoadError": "Error loading file",
  "clickToRetry": "Tap to try again",
  "videoLoading": "Loading video",
  "editorAiConfirm": "Confirm AI-generated content first",
  "editorAiMacPlaceholder": "Start writing or press the Command key twice to wake up AI Creation",
  "noteConflict": "Multi-device conflicting note {0} {1}",
  "tuyaLoading": "Loading doodle",
  "videoLoadError": "Error loading video",
  "noteUnSupported": "Some content and styles in this note cannot be properly displayed. Update to the latest version.",
  "editorAiWinPlaceholder": "Start writing or press Alt twice to activate AI Creation",
  "videoCannotLoad": "Unable to load video",
  "fileCannotLoad": "Unable to load document",
  "editorAiLimitReached": "Too many AI Creation attempts",
  "audioLoading": "Loading audio",
  "imgCannotError": "Unable to load image",
  "audioLoadError": "Error loading audio",
  "startWritingOrDoubleClickCommand": "Start writing or press the Command key twice to wake up AI Creation",
  "cannotEditNoteDuringAiCreation": "Cannot edit note while AI Creation is in progress",
  "emptyPlaceholderPleaseCheckInfo": "{0} is empty. Check {0} information",
  "documentCountCannotExceedLimit": "Document quantity cannot exceed {0}",
  "creationInProgressMessage": "Creating…",
  "clickToSwitchAndViewGeneratedResults": "Click to switch and view generation result",
  "audioCountCannotExceedLimit": "Audio file quantity cannot exceed {0}",
  "discard": "Discard",
  "arabic": "Arabic",
  "italian": "Italian",
  "stopGenerating": "Stop",
  "chineseSimplified": "Simplified Chinese",
  "invalidFileNameCharactersDetected": "The filename cannot contain any of the following characters: carriage return, emoji, \\\\, /, :, *, ?, \", <, >, and |",
  "maxAttachmentSupportedLimitExceeded": "The maximum allowed size for an uploaded attachment is {0}.",
  "multideviceConflictNote": "Multi-device note conflict {0} {1}",
  "recordingCountCannotExceedLimit": "Recording quantity cannot exceed {0}",
  "enterContentToUseAiCreation": "Enter content to use the AI Creation feature",
  "fileLoading": "Loading file",
  "aiWriting": "AI Creation",
  "spanish": "Spanish",
  "german": "German",
  "nextResult": "Next result",
  "partialContentNotTranscribedInRecording": "Part of this recording is not transcribed.",
  "file": "File",
  "imageCountCannotExceedLimit": "Image quantity cannot exceed {0}",
  "commandNotSupportedForContentOverLimit": "This prompt cannot process content over {0} characters",
  "clickWillInterruptAiGeneration": "Clicking will interrupt the AI generation process",
  "generating...": "Generating…",
  "officeSoftwareNotDetected": "No Office app detected",
  "startWritingOrDoubleClickAlt": "Start writing or press Alt twice to activate AI Creation",
  "writeLimitReached": "Too many AI Creation attempts",
  "thai": "Thai",
  "french": "French",
  "korean": "Korean",
  "keyPointPlaceholder": "Key point {0}:",
  "indonesian": "Indonesian",
  "portuguese": "Portuguese",
  "replaceSelection": "Replace selection",
  "confirmInsert": "Insert",
  "previousResult": "Previous result",
  "vietnamese": "Vietnamese",
  "pleaseConfirmAiGeneratedContent": "Confirm AI-generated content first",
  "videoCountCannotExceedLimit": "Video quantity cannot exceed {0}",
  "pleaseWaitMessage": "Please wait…",
  "chineseTraditional": "Traditional Chinese",
  "hindi": "Hindi",
  "russian": "Russian",
  "english": "English",
  "japanese": "Japanese",
  "noteToolbarInterconnectDialogBtn2": "Discard",
  "smartFormatting": "Smart layout",
  "minimumCharacterRequirement2": "Select at least 200 characters to use Summarize",
  "translationFeature": "Translate",
  "minimumCharacterRequirement1": "Select at least 200 characters to use Smart layout",
  "todoExtraction": "Extract to-dos",
  "summaryGeneration": "Summarize",
  "noAssociatedApp": "No apps detected to open this file",
  "deleteSelectedColumns": "Delete selected columns",
  "copyFailed": "Failed to copy. Try again",
  "parsingRecording": "Parsing the recording",
  "textLoadError": "Text loading error",
  "generatingStatus": "Generating…",
  "pasteShortcutNotice": "Use ⌘/Ctrl+V to paste",
  "recordingType2": "recording",
  "pasteShortcutTip": "Use ⌘/Ctrl+V to paste",
  "confidentialNotice": "Do not share",
  "transcriptionFailedNotice": "Failed to transcribe",
  "networkErrorNotice": "Network error. Check your network connection",
  "networkError": "Network error. Check your network connection",
  "moreCommands": "More prompts",
  "inputLimitReached": "Character limit reached for input box",
  "templatePlaceholderText": "This is a text template. This is sample text. Replace it with your own text. You can change the template's color and style.",
  "unsupportedElement": "This app version does not support {0} displaying",
  "recordingFailed": "Failed to record",
  "manageHistoryCommands": "Manage prompt history",
  "usageLimitReached": "Too many AI Creation attempts",
  "documentType2": "document",
  "characterLimitExceeded": "Character limit reached",
  "deleteTable": "Delete table",
  "retryTranscription": "Retry",
  "copySuccess": "Copied",
  "limitExceededWarning": "Character limit reached",
  "openAction": "Open",
  "applyToAllTextStyles": "Apply to all text styles",
  "transcriptionEnabled": "Transcription on",
  "insufficientContentWarning": "Insufficient content for summarization",
  "refreshButton": "Tap to refresh",
  "historyToggleNotice": "Tap to switch and view historical generation results",
  "sizeXL": "Extra large",
  "largeImageMode": "Large image mode",
  "sizeSmall": "Thin",
  "deleteItem": "Delete",
  "deleteAction": "Delete",
  "desktopEditRestriction": "Editing recording-related content unavailable on your computer",
  "cutShortcutReminder": "Cutting via right-click unavailable. Use ⌘/Ctrl+X",
  "copyShortcutReminder": "Copying via right-click unavailable. Use ⌘/Ctrl+C",
  "networkWarning": "Network error. Check your network connection",
  "micUnavailable": "No available microphone",
  "loadingRecording": "Loading recording",
  "presetCommands": "Preset prompt",
  "rowLimitExceeded": "Row limit reached",
  "nRow": "{0} row",
  "dotFilenameError": "Failed to modify. The filename cannot start with \".\"",
  "documentType1": "Document",
  "columnLimitExceeded": "Column limit reached",
  "thisData": "This app version does not support displaying this data.",
  "nRows": "{0} rows",
  "deleteRowColumn": "Delete rows and columns",
  "contentLimitExceeded": "Character limit reached",
  "emptyFilenameError": "Failed to change. Filename cannot be empty",
  "realTimeTranscribeTip": "Tap to transcribe during recording",
  "noMicrophone": "No available microphone",
  "cutRightclickNotice": "Cutting via right-click unavailable. Use ⌘/Ctrl+X",
  "imageCountLabel": "Image count",
  "summaryLabel": "Summary:",
  "expandAction": "Expand",
  "copySuccessNotice": "Copied",
  "renameAction": "Rename",
  "historyCommands": "Command history",
  "generatingSuggestions": "Generating recommended questions",
  "unsupportedFeature2": "Cut unavailable. Use ⌘/Ctrl+X",
  "nColumns": "{0} columns",
  "insertMultiRight": "Insert {0} columns to the right",
  "insertMultiAbove": "Insert {0} rows above",
  "clearCell": "Clear cells",
  "transcribeButton": "Tap to transcribe",
  "durationLimitReached": "Recording duration limit reached",
  "enableMicPermission": "Make sure the Microphone permission is enabled",
  "partialTranscriptionNotice": "Part of this recording is not transcribed.",
  "transcribingStatus": "Transcribing…",
  "generatingSummary": "Generating summary. Please wait",
  "aiSummaryLabel": "AI Summary",
  "applyToAllSymbols": "Apply to all symbols",
  "insertAbove": "Insert {0} row above",
  "attachmentSizeLimit": "The {0} size cannot exceed 200 MB",
  "spaceFilenameError": "Failed to modify. The filename cannot be only spaces",
  "summaryAvailableNotice": "A summary can be generated after recording ends",
  "pleaseWaitNotice": "Please wait…",
  "insertBelow": "Insert {0} row below",
  "textLoadingStatus": "Loading text…",
  "videoType2": "video",
  "unstructuredContentError": "Fragmented content. Unable to generate a summary",
  "themeLabel": "Subject:",
  "originalTextLabel": "Transcript",
  "copyAction": "Copy",
  "audioType1": "Audio",
  "emptyInputNotice": "Enter requirements in the input box",
  "sizeL": "Large",
  "pasteAction": "Paste",
  "insertLeft": "Insert {0} column to the left",
  "unsupportedContentNotice": "Editing this content unavailable for the current app version",
  "transcriptionLimitReached": "Transcription reached the character limit",
  "unfinishedOperationAlert": "Recording unfinished. Unable to perform action",
  "transcriptionLimitWarning": "Transcription will reach the 12,000 character limit and recording will automatically stop and save.",
  "untitledRecording": "Untitled recording",
  "additionalInputPrompt": "Add details",
  "itemCountLabel": "Item count",
  "maxRowsReached": "Row limit reached",
  "insertRight": "Insert {0} column to the right",
  "insertMultiBelow": "Insert {0} rows below",
  "unfinishedDeleteWarning": "Recording unfinished. Unable to delete",
  "textParsingStatus": "Parsing text…",
  "recordingTimeLimitWarning": "Recording will reach the 2-hour limit and automatically stop and save.",
  "unsupportedFeatureNotice": "Copy unavailable. Use ⌘/Ctrl+C",
  "attachmentAddGenericError": "{0} addition failed",
  "audioType2": "audio",
  "applyToAllDividers": "Apply to all parting lines",
  "doodleLabel": "Doodles",
  "cutSuccess": "Cut successful",
  "unfinishedTranscriptionNotice": "{0}–{1} of this recording is not transcribed. {2}",
  "sizeXS": "Small",
  "textLimitExceeded": "Character limit reached",
  "recordingSavedNotice": "Recording saved",
  "imageType1": "Image",
  "todoLabel": "To-do:",
  "headingLabel": "Title",
  "copyTextAction": "Copy text",
  "cutAction": "Cut",
  "maxCharactersReached": "Character limit reached",
  "recordingType1": "Recording",
  "sizeStandard": "Standard",
  "historySectionLabel": "Command history",
  "commandDisabled": "Command unavailable",
  "requestLimitReached": "Request limit reached",
  "sizeLarge": "Thick",
  "downloadAction": "Download",
  "elementReplaceDisabled": "Replacement unavailable for this element",
  "summaryFailed": "Failed to generate",
  "characterCountLabel": "Word count:",
  "imageType2": "image",
  "upgradeRequired": "Update to the latest version",
  "nColumn": "{0} column",
  "cellCharacterLimit": "Cell word limit reached",
  "deleteSelectedRows": "Delete selected rows",
  "cutSuccessNotice": "Cut successful",
  "versionUpgradeNotice": "Some of the content and styles in this note cannot be properly displayed. Update to the latest version.",
  "aiGeneratedDisclaimer": "The above content is generated by BlueLM and is for reference only.",
  "microphoneDisabled": "Microphone permission not enabled",
  "copyRightclickNotice": "Copying via right-click unavailable. Use ⌘/Ctrl+C",
  "entryCountLabel": "Item entry count",
  "reTranscribeAction": "Transcribe again",
  "saveAsAction": "Save as",
  "insertMultiLeft": "Insert {0} columns to the left",
  "insertRowColumn": "Insert rows and columns",
  "pauseToEditNotice": "Text can be edited after you pause recording",
  "writingAssistant": "AI Creation",
  "generatingSummaryProgress": "Generating summary. Please wait",
  "transcriptionDisabled": "Transcription off",
  "generatingSummaryStatus": "Generating summary. Please wait",
  "permissionDenied": "Access denied",
  "transcriptionFailed": "Failed to transcribe",
  "selectionLengthError": "This prompt cannot process content over {0} characters",
  "aiPromptInputHint": "Enter a creation requirement or choose a prompt from the list",
  "attachmentAddPermissionError": "{0} addition failed. Enable the Access permission",
  "collapseAction": "Collapse",
  "retryAction": "Retry",
  "smallImageMode": "Small image mode",
  "transcribingNotice": "Transcription in progress. Please wait",
  "recordingSaved": "Recording and text saved",
  "noSummaryContent": "No content for summarization",
  "refreshPrompt": "Tap to refresh",
  "videoType1": "Video"
});
